### ISSUE TITLE
Route Configuration

### ISSUE THREAD

**Issue by ryan-hamblin** [Lambda-School-Labs/labs-fe#1]
We need to set up Routing inside the application. 

Routes should be:
- [ ] index -> mounts header (navbar) persisted across all routes w/ links to different UI.

- [ ] /attendence-tracker -> mounts a form (@ryan to include image from the prototype that Frank)

- [ ] /login -> form that mounts Okta's signin widget

**Comment by ryan-hamblin** [comment]
Let's focus on JUST mounting the UI and stubbing out any calls to the API.

**Comment by frankfusco** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FE route configuration](https://trello.com/c/6ysvGt2d/12-fe-route-configuration)
